---
# =============================================
#   INSTALL CLICKHOUSE
# =============================================

- name: "Install Clickhouse"
  hosts: clickhouse
  roles:
    - role: "clickhouse"

# =============================================
#   INSTALL VECTOR
# =============================================

- name: "Install Vector"
  hosts: vector
  roles:
    - role: "vector"

# =============================================
#   INSTALL LIGHTHOUSE
# =============================================

- name: "Install Lighthouse"
  hosts: lighthouse
  roles:
    - role: "lighthouse"
